# Generated by Django 4.2.3 on 2023-07-31 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_wishlist_wishlistproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dateAdded',
            field=models.DateField(blank=True, null=True),
        ),
    ]
