# Generated by Django 4.2.3 on 2023-08-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_category_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='coverPhoto',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
