# Generated by Django 4.2.3 on 2023-08-07 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_shoppingcart_id_alter_wishlist_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='item',
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='quantity',
        ),
        migrations.AddField(
            model_name='orderitems',
            name='cart_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.cartproducts'),
        ),
    ]
